# Generated by Django 6.1 on 2026-08-18 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Rating must be form 0 to 5 stars'), django.core.validators.MaxValueValidator(5, 'Rating must be from 0 to 5 stars')])),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='movies.movie')),
            ],
        ),
    ]
